spring:
  config:
    import:
      - optional:classpath:config/application-core.yml
      - optional:classpath:config/application-redis.yml
      - optional:classpath:config/application-member.yml

server:
  port: 8084
